# Generated by Django 4.0.6 on 2022-08-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomment',
            options={'verbose_name': 'Ответ на новость', 'verbose_name_plural': 'Ответы на новость'},
        ),
    ]
