# Generated by Django 4.0.6 on 2022-08-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newscomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
