# Generated by Django 4.0.6 on 2022-07-27 12:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория роли',
                'verbose_name_plural': 'Категория ролей',
            },
        ),
        migrations.CreateModel(
            name='HeroesSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_skill', ckeditor_uploader.fields.RichTextUploadingField()),
                ('second_skill', ckeditor_uploader.fields.RichTextUploadingField()),
                ('third_skill', ckeditor_uploader.fields.RichTextUploadingField()),
                ('passive_skill', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Скилл',
                'verbose_name_plural': 'Скиллы',
                'db_table': 'skills_db',
            },
        ),
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=150)),
                ('complexity', models.IntegerField(default=0, null=True)),
                ('description', models.TextField()),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='heroes.heroescategories')),
                ('skill', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='heroes.heroesskills')),
            ],
            options={
                'verbose_name': 'Герой',
                'verbose_name_plural': 'Герои',
                'db_table': 'heroes_db',
            },
        ),
    ]
