# Generated by Django 4.0.6 on 2022-07-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroescategories',
            old_name='role',
            new_name='key_role',
        ),
    ]
