# Generated by Django 4.0.6 on 2022-08-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_rename_role_heroescategories_key_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesskills',
            name='image_first',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='heroesskills',
            name='image_second',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='heroesskills',
            name='image_third',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
