# Generated by Django 4.0.6 on 2022-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_alter_heroesskills_image_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesskills',
            name='image_passive',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
