# Generated by Django 4.0.6 on 2022-08-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_heroesskills_image_passive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heroes',
            new_name='Hero',
        ),
        migrations.RenameModel(
            old_name='HeroesCategories',
            new_name='HeroCategories',
        ),
        migrations.RenameModel(
            old_name='HeroesSkills',
            new_name='HeroSkills',
        ),
    ]
